In [24]:
import numpy as np
import pandas as pd
from pathlib import Path

source = '/cosma5/data/durham/dc-pick2/simulations'

import experiments as e
import importlib
importlib.reload(e)

/cosma/home/durham/dc-pick2/Globular/experiments.py:27: SyntaxWarning: invalid escape sequence '\o'
  GalacticMass  = ExperimentInfo(name='GalacticMass', label=r'$M_d$', unit='$M_\odot$', sciNot=True, formattable=True)

In [21]:
%run utils.ipynb

In [17]:
path = source + '/Hyades2'
df = Make_timestep_df(path)
df

creating /cosma5/data/durham/dc-pick2/simulations/Hyades2/stepdata.csv

       Time[Myr]     Step                                               Snap
0       0.000000   Step#0  /cosma5/data/durham/dc-pick2/simulations/Hyade...
1       0.301211   Step#1  /cosma5/data/durham/dc-pick2/simulations/Hyade...
2       0.602422   Step#2  /cosma5/data/durham/dc-pick2/simulations/Hyade...
3       0.903633   Step#3  /cosma5/data/durham/dc-pick2/simulations/Hyade...
4       1.204844   Step#4  /cosma5/data/durham/dc-pick2/simulations/Hyade...
...          ...      ...                                                ...
2324  700.014305  Step#83  /cosma5/data/durham/dc-pick2/simulations/Hyade...
2325  700.315516  Step#84  /cosma5/data/durham/dc-pick2/simulations/Hyade...
2326  700.616727  Step#85  /cosma5/data/durham/dc-pick2/simulations/Hyade...
2327  700.917938  Step#86  /cosma5/data/durham/dc-pick2/simulations/Hyade...
2328  701.219149  Step#87  /cosma5/data/durham/dc-pick2/simulations/Hyade...

[2329 rows x 3 columns]

In [18]:
pd.read_csv(path + '/stepdata.csv')

       Time[Myr]     Step                                               Snap
0       0.000000   Step#0  /cosma5/data/durham/dc-pick2/simulations/Hyade...
1       0.301211   Step#1  /cosma5/data/durham/dc-pick2/simulations/Hyade...
2       0.602422   Step#2  /cosma5/data/durham/dc-pick2/simulations/Hyade...
3       0.903633   Step#3  /cosma5/data/durham/dc-pick2/simulations/Hyade...
4       1.204844   Step#4  /cosma5/data/durham/dc-pick2/simulations/Hyade...
...          ...      ...                                                ...
2324  700.014305  Step#83  /cosma5/data/durham/dc-pick2/simulations/Hyade...
2325  700.315516  Step#84  /cosma5/data/durham/dc-pick2/simulations/Hyade...
2326  700.616727  Step#85  /cosma5/data/durham/dc-pick2/simulations/Hyade...
2327  700.917938  Step#86  /cosma5/data/durham/dc-pick2/simulations/Hyade...
2328  701.219149  Step#87  /cosma5/data/durham/dc-pick2/simulations/Hyade...

[2329 rows x 3 columns]

In [25]:
for ex in e.exlist:
    experiment_path = Path(source) / ex.name
    for run in get_runs(experiment_path):
        path = experiment_path / str(run)
        
        if not (path / 'stepdata.csv').exists():
            #print(path)
            Make_timestep_df(path)
            
print('done')

creating /cosma5/data/durham/dc-pick2/simulations/GalacticMass/10000000000.0/stepdata.csv

FileNotFoundError: [Errno 2] No such file or directory: '/cosma5/data/durham/dc-pick2/simulations/GalacticMass/10000000000.0/global.30'